#!/bin/bash

set -euo pipefail
. /.functions

usage()
{
	echo -e "usage ${BASH_ARG0:-${BASH_SOURCE:-${0}}} ARTIFACT_ID OLD_VERSION_MAJOR NEW_VERSION NEW_JAR"
	exit 1
}

[ ${#} -eq 4 ] || usage

set_or_default BASE_DIR "/app"
set_or_default HOME_DIR "${BASE_DIR}/solr"
set_or_default LICENSES_DIR "${HOME_DIR}/licenses"

ARTIFACT_ID="${1}"
OLD_VERSION_MAJOR="${2}"
NEW_VERSION="${3}"
NEW_JAR="${4}"

JAR_NAME="${NEW_JAR##*/}"

SHA1_NAME="${LICENSES_DIR}/${JAR_NAME}.sha1"

# Don't compute it twice, not needed
[ -e "${SHA1_NAME}" ] && exit 0

find "${LICENSES_DIR}" -type f -name "${ARTIFACT_ID##*:}-${OLD_VERSION_MAJOR}.*.jar.sha1" -delete -print
sha1sum "${NEW_JAR}" | awk '{ print $1 }' > "${SHA1_NAME}"
